# disable Spring MVC
spring:
  main:
    web-application-type: none

tacocloud:
  api:
    url: http://localhot:8080/order/fromEmail
  email:
    host: imap.tacocloud.com
    mailbox: INBOX
    username: taco-in-flow
    password: 1L0v3T4c0s
    poll-rate: 10000